### ISSUE TITLE
UTF-8 letters with accent

### ISSUE THREAD

**Issue by djibe** [iuccio/csvToJson#10]
Hi guys,
with the french csv in attachment, there are accents on some letters.
How to keep these in the JSON output ?
I get lines like this : 
"l_ATC1": "Syst�me digestif et m�tabolisme",

Thanks a lot.
[openmedictest.zip](https://github.com/iuccio/csvToJson/files/3101534/openmedictest.zip)

**Comment by Gethi** [comment]
You need to use `iconv-lite` to encode in `latin1` 

Proposal : 
FileUtils.readFile(fileInputName, encoding)

In the meantime here a package:
https://www.npmjs.com/package/convert-csv-to-json-latin

**Comment by iuccio** [comment]
@Gethi , @djibe 

the release [v.1.2.0](https://github.com/iuccio/csvToJson/releases/tag/v1.2.0) solved this problems see the documentation: [Encoding](https://github.com/iuccio/csvToJson#encoding). Please check if it works for you  :-)

**Comment by djibe** [comment]
Thanks a lot.
Well done.
I'll try ASAP
