### ISSUE TITLE
Doesn't handle new line characters inside of data row

### ISSUE THREAD

**Issue by andreweinhorn** [iuccio/csvToJson#14]
If there are newline characters within a particular column of data, csvToJson thinks it has reached the end of the row.  I'm not sure if this means I need to find a way to avoid newline characters appearing in the data, but because some of my data cells contain multiple paragraphs of text, I am not sure how to get around this.

**Comment by iuccio** [comment]
The newline characters is used to get the end of the row. I don't have others solutions to get the new line.
You can use, for example, the HTML Tag `<p></p>` to mark the paragraph.
