### ISSUE TITLE
Uploading CSV file for conversion

### ISSUE THREAD

**Issue by Pattygeek** [iuccio/csvToJson#17]
Please at what point do I upload the csv file bofore the conversion?

**Comment by Pattygeek** [comment]
In my app, the csv file is not local, users upload different csv file and I want to convert the csv to json before sending it to the backend.

**Comment by TalalBhatti** [comment]
I'm using the code but it is giving me 
 {
  "Date,Time,Temperature,ais,ais,ais": "04/13/21,18:26,70.12,0.71,-2.12,11.02"
 }
 instead of 
{
"Date": "04/13/21",
"Time": "18:26",
Temperature":70.12,
.....
}

**Comment by JustinHarshbarger** [comment]
@iuccio I recommend this just be closed as there are two unrelated issues. One is a fundamental app design issue and not related to the library, the other looks like a problem with having the default using ; (which I feel is an unexpected choice). Both are not bugs and are not enhancement requests.

I don believe the next major version bump should change to comma split by default.
