### ISSUE TITLE
I'm using the code but it is giving me

### ISSUE THREAD

**Issue by iuccio** [iuccio/csvToJson#18]
I'm using the code but it is giving me 
 {
  "Date,Time,Temperature,ais,ais,ais": "04/13/21,18:26,70.12,0.71,-2.12,11.02"
 }
 instead of 
{
"Date": "04/13/21",
"Time": "18:26",
Temperature":70.12,
.....
}

_Originally posted by @TalalBhatti in https://github.com/iuccio/csvToJson/issues/17#issuecomment-828057337_

**Comment by iuccio** [comment]
@TalalBhatti Please give me the csv data example

**Comment by TalalBhatti** [comment]
Sure, PFA
My code:

let csvToJson = require('convert-csv-to-json');
let fileInputName = 'myInputFile.csv'; let fileOutputName = 'myOutputFile.json';
csvToJson.generateJsonFileFromCsv(fileInputName,fileOutputName);

**Comment by iuccio** [comment]
@TalalBhatti I need an example of the CSV file you are using to be able to understand the problem.

**Comment by TalalBhatti** [comment]
[tosend.csv](https://github.com/iuccio/csvToJson/files/6401205/tosend.csv)

**Comment by iuccio** [comment]
@TalalBhatti the problem is the field delimiter. As in the readme specified, the default field delimiter is the semicolon (;). This means that the parsed values are splitted when a semicolon is matched. See the chapter [Define field delimiter](https://github.com/iuccio/csvToJson#define-field-delimiter). In your case, in your CSV file, the field delimiter is the comma. In this case you have to define as a field delimiter the comma **,**:
   
csvToJson.**fieldDelimiter(',')**.generateJsonFileFromCsv(fileInputName,fileOutputName);

Here the solution: 

```
let csvToJson = require('convert-csv-to-json');
let fileInputName = 'myInputFile.csv'; 
let fileOutputName = 'myOutputFile.json';
csvToJson.fieldDelimiter(',').generateJsonFileFromCsv(fileInputName,fileOutputName);
```
I tried it with your file, here below the result:
```
[
 {
  "Date": "04/13/21",
  "Time": "18:26",
  "Temperature": "70.12 *C",
  "Xaxis": "0.71 X",
  "Yaxis": "-2.12 Y",
  "Zaxis": "11.02 Z "
 },
...
]
```

**Comment by TalalBhatti** [comment]
Thanks a lot
