### ISSUE TITLE
String "ID" conversion error

### ISSUE THREAD

**Issue by lako12** [iuccio/csvToJson#28]
Hi guys

I have this CSV file
![image](https://user-images.githubusercontent.com/58422683/157059125-d998f983-1e35-4d17-9ecc-f6274c10af3a.png)
The problem is that the text of the ID column is converted as ""ID"" 
So I will have this json:
{
    "MODULE" : "TEST",
    "TABLE" : ""ID"",
    "DESC" : "id"
}

can you help me?
Thanks

**Comment by lako12** [comment]
do you have any solution?

**Comment by iuccio** [comment]
I can't reproduce. Can you upload the file?

**Comment by JustinHarshbarger** [comment]
@iuccio Recommend close as issue is stale and not reproducible.

**Comment by iuccio** [comment]
not reproducible.
