### ISSUE TITLE
If the csv file have headers with spaces ( Product Name) then getJsonFromCsv() method is creating the keys without the any space(ProductName)

### ISSUE THREAD

**Issue by raghub20** [iuccio/csvToJson#29]
## Issue description:
When the user tries to generate a json object form csv file which contains words as column header, getJsonFromCsv() method returned json object have keys by excluding spaces of the column headers.

Ex:
product-wise-users.csv
Product Name, Unique Users
Java, 100
Javascript, 140

product-wise-users.json
[
   {
       "ProductName": "Java",
        "UniqueUsers": "100"
   },
  {
       "ProductName": "Javascript",
        "UniqueUsers": "140"
   }
]

**Comment by iuccio** [comment]
In this project any string content get trimmed. This is a feature, as a best practice, to avoid to work with strings that contain prefix or postfix white spaces.
I'm sorry but I will not change this behavior.

**Comment by 50bbx** [comment]
An option to toggle this on or off would be a nice idea

**Comment by vivekdev0** [comment]
so removing spaces from the ends is fine
but this is not just trimming, but it is removing spaces from the middle.
don't have a strong opinion yet, but have to look for a different lib now

**Comment by octavio12345300** [comment]
👍
