### ISSUE TITLE
array in csv file

### ISSUE THREAD

**Issue by mafrego** [iuccio/csvToJson#3]
Hi iuccio,
what if I have a csv file like this:

father, son(s), daughter(s)                                           //headerline

Antonio, Beppe:Gino:Luca, Maria                                //an array with 3 sons, ":" colon as value separator
Roberto, Francesco, Silvia:Laura                                //an array with 2 daugthers

Thanks!

**Comment by iuccio** [comment]
@mafrego 
With the release [v1.3.0](https://github.com/iuccio/csvToJson/releases/tag/v1.3.0) you can generate JSON object with sub array. 
Please check if it works for you :-)
