### ISSUE TITLE
Delimiter part of the text

### ISSUE THREAD

**Issue by sivaram-vu** [iuccio/csvToJson#8]
If delimiter is part of the value, then the value is not captured properly. 

let json = csvToJson.fieldDelimiter(',').getJsonFromCsv(path);
If comma is part of the value, then json has incorrect values.

**Comment by iuccio** [comment]
Instead of "," you can define something else as field delimiter.

**Comment by Riotsmurf2** [comment]
Yikes

**Comment by iuccio** [comment]
If someone of you have a solution, please make a PR! I will merge it.
