### ISSUE TITLE
 JavaScript heap out of memory

### ISSUE THREAD

**Issue by dobrun** [iuccio/csvToJson#9]
When I execute `generateJsonFileFromCsv(fileInputName,fileOutputName)` I get a memory error.

0: ExitFrame [pc: 0A25209E]
Security context: 0x0af12701 <JSObject>
    1: csvToJson [0772CA71] [C:\Users\dbr\node_modules\convert-csv-to-json\src\csvToJson.js:~39] [pc=21E33849](this=0x07730cdd <CsvToJson map = 29BAC2F5>,parsedCsv=0x3f204101 <Very long string[74904862]>)
    2: getJsonFromCsv [0772CA55] [C:\Users\dbr\node_modules\convert-csv-to-json\src\csvToJson.js:36] [bytecode=087DA291 offset=26](this=0x07730cdd <CsvToJson map = 2...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0103150E
 2: 0168AE42
 3: 01681BE1
 4: 016892DE

**Comment by iuccio** [comment]
How big is your file?

**Comment by shershin** [comment]
@iuccio I am also having this issue and my files can range anywhere from next to nothing to a decent sized 4gb

**Comment by iuccio** [comment]
Here maybe the solution: https://stackoverflow.com/questions/38558989/node-js-heap-out-of-memory
